### ISSUE TITLE
can't create arena

### ISSUE THREAD

**Issue by belette75** [iZeaoGamer/Eggwars#3]
sorry if i open new issue but same error message after

git pull origin master

regards

**Comment by iZeaoGamer** [comment]
Please send the error log. Thanks.

**Comment by belette75** [comment]
same message

 [Server thread/CRITICAL]: Unhandled exception executing command 'ew c
reate desert 2 1' in ew: Argument 1 passed to Driesboy\EggWars\EggWars::ArenaCre
ate() must be an instance of Driesboy\EggWars\Arena, string given, called in /ho
me/belette/tutu/PocketMine-MP-master/plugins/Eggwars/src/Driesboy/EggWars/Comman
d/EW.php on line 42

 [Server thread/CRITICAL]: TypeError: "Argument 1 passed to Driesboy\E
ggWars\EggWars::ArenaCreate() must be an instance of Driesboy\EggWars\Arena, str
ing given, called in /home/belette/tutu/PocketMine-MP-master/plugins/Eggwars/src
/Driesboy/EggWars/Command/EW.php on line 42" (EXCEPTION) in "Eggwars/src/Driesbo
y/EggWars/EggWars" at line 211
